### ISSUE TITLE
Code completion doesn't work with cmake installed via snap. 

### ISSUE THREAD

**Issue by ltruciosr** [twxs/vs.language.cmake#65]
I've installed vscode and cmake via snap in Ubuntu 20.04, for any reason autocomplete isn't working, although it's able to recognize a parameter after being written. 
cmake -- 3.17.3

**Comment by twxs** [comment]
I never used it but if I understand snap seems to be a bundle. May be you need to adjust the cmakePath setting.

**Comment by dbird137** [comment]
@twxs 
cmake-tools has the same issue with snap versions of CMake: https://github.com/microsoft/vscode-cmake-tools/issues/838

@ltruciosr 
I had the same problem and tried monkeying around with the paths in VSCode and the snap itself.  Eventually I gave up on the snap version altogether.  It's unfortunate that the version of CMake from ubuntu's main 20.04 repo is only at 3.16.3 because installing it with apt has no path problems with either the cmake-language or cmake-tools extensions.  It's also unfortunate that the Linux binary downloads from [cmake.org](https://cmake.org/download/) make it weirdly difficult to install in a sane way.  If you need 3.17 or newer I'd highly recommend downloading and compiling from source.  Once everything is extracted it's literally just this command to build and install it into the proper distro-specific paths. 
```
$ ./bootstrap && make && sudo make install
```
Then you can double check that it's in your path with `cmake --version` from anywhere.

**Comment by ltruciosr** [comment]
Thanks @dbird137 
It was exactly what I was looking for, I have also adjusted the cmakePath setting to use the cmake installed with apt instead of the ones installed with snap.
